name: Build and deploy Hugo site to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true  # important: fetch theme submodule

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.115.0'   # or latest stable version

      - name: Build
        run: hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable GitHub Pages (optional)
        uses: crazy-max/ghaction-github-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
